### ISSUE TITLE
LocalJumpError: unexpected return on 1.19.0

### ISSUE THREAD

**Issue by lloeki** [sqreen/ruby-agent#1]
From https://github.com/scoutapp/scout_apm_ruby/issues/278#issuecomment-636903910 by @hashwin.

> while it seems to work OK for scout, I am getting an error in another place "LocalJumpError: unexpected return" when opening `delayed_job_web`:

```
2020-06-01T14:33:41.620007+00:00 app[web.1]: 2020-06-01 14:33:41 +0000: Rack app error handling request { GET /working }
2020-06-01T14:33:41.620009+00:00 app[web.1]: #<LocalJumpError: unexpected return>
2020-06-01T14:33:41.620013+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/sqreen-1.19.0/lib/sqreen/weave/legacy/instrumentation.rb:305:in `block (2 levels) in add_callback'
2020-06-01T14:33:41.620014+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/sqreen-1.19.0/lib/sqreen/graft/callback.rb:26:in `call'
2020-06-01T14:33:41.620014+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/sqreen-1.19.0/lib/sqreen/graft/hook.rb:260:in `block (7 levels) in wrapper'
2020-06-01T14:33:41.620015+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/sqreen-1.19.0/lib/sqreen/graft/call.rb:119:in `ignore'
2020-06-01T14:33:41.620015+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/sqreen-1.19.0/lib/sqreen/graft/hook.rb:259:in `block (6 levels) in wrapper'
2020-06-01T14:33:41.620015+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/sqreen-1.19.0/lib/sqreen/graft/call.rb:126:in `measure'
2020-06-01T14:33:41.620016+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/sqreen-1.19.0/lib/sqreen/graft/hook.rb:258:in `block (5 levels) in wrapper'
2020-06-01T14:33:41.620016+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/sqreen-1.19.0/lib/sqreen/graft/hook.rb:255:in `catch'
2020-06-01T14:33:41.620016+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/sqreen-1.19.0/lib/sqreen/graft/hook.rb:255:in `block (4 levels) in wrapper'
2020-06-01T14:33:41.620017+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/sqreen-1.19.0/lib/sqreen/graft/hook.rb:244:in `each'
2020-06-01T14:33:41.620017+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/sqreen-1.19.0/lib/sqreen/graft/hook.rb:244:in `block (3 levels) in wrapper'
2020-06-01T14:33:41.620018+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/sqreen-1.19.0/lib/sqreen/graft/call.rb:126:in `measure'
2020-06-01T14:33:41.620018+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/sqreen-1.19.0/lib/sqreen/graft/hook.rb:243:in `block (2 levels) in wrapper'
2020-06-01T14:33:41.620018+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/sqreen-1.19.0/lib/sqreen/graft/call.rb:126:in `measure'
2020-06-01T14:33:41.620019+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/sqreen-1.19.0/lib/sqreen/graft/hook.rb:126:in `block in wrapper'
2020-06-01T14:33:41.620019+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.10.0.364/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
2020-06-01T14:33:41.620020+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'
2020-06-01T14:33:41.620020+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.10.0.364/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
2020-06-01T14:33:41.620021+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.2.2/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
2020-06-01T14:33:41.620021+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.10.0.364/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
2020-06-01T14:33:41.620022+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.2.2/lib/action_dispatch/middleware/executor.rb:14:in `call'
```

**Comment by lloeki** [comment]
@hashwin I have identified the issue and fixed it on master. A release will be issued shortly.
