### ISSUE TITLE
Rack app error handling request on 1.19.1

### ISSUE THREAD

**Issue by hashwin** [sqreen/ruby-agent#2]
```
Rack app error handling request { GET /api/v1/leads/1766764 }
#<NoMethodError: undefined method `[]' for #<Set: {"headers", "rule", "request", "local"}>>
2020-06-03T04:33:03.179574+00:00 app[web.2]: /app/vendor/bundle/ruby/2.6.0/gems/sqreen-1.19.1/lib/sqreen/weave/legacy/instrumentation.rb:325:in `block (2 levels) in add_callback'
2020-06-03T04:33:03.179574+00:00 app[web.2]: /app/vendor/bundle/ruby/2.6.0/gems/sqreen-1.19.1/lib/sqreen/graft/callback.rb:26:in `call'
2020-06-03T04:33:03.179575+00:00 app[web.2]: /app/vendor/bundle/ruby/2.6.0/gems/sqreen-1.19.1/lib/sqreen/graft/hook.rb:260:in `block (7 levels) in wrapper'
2020-06-03T04:33:03.179576+00:00 app[web.2]: /app/vendor/bundle/ruby/2.6.0/gems/sqreen-1.19.1/lib/sqreen/graft/call.rb:119:in `ignore'
2020-06-03T04:33:03.179576+00:00 app[web.2]: /app/vendor/bundle/ruby/2.6.0/gems/sqreen-1.19.1/lib/sqreen/graft/hook.rb:259:in `block (6 levels) in wrapper'
2020-06-03T04:33:03.179576+00:00 app[web.2]: /app/vendor/bundle/ruby/2.6.0/gems/sqreen-1.19.1/lib/sqreen/graft/call.rb:126:in `measure'
2020-06-03T04:33:03.179577+00:00 app[web.2]: /app/vendor/bundle/ruby/2.6.0/gems/sqreen-1.19.1/lib/sqreen/graft/hook.rb:258:in `block (5 levels) in wrapper'
2020-06-03T04:33:03.179577+00:00 app[web.2]: /app/vendor/bundle/ruby/2.6.0/gems/sqreen-1.19.1/lib/sqreen/graft/hook.rb:255:in `catch'
2020-06-03T04:33:03.179578+00:00 app[web.2]: /app/vendor/bundle/ruby/2.6.0/gems/sqreen-1.19.1/lib/sqreen/graft/hook.rb:255:in `block (4 levels) in wrapper'
2020-06-03T04:33:03.179578+00:00 app[web.2]: /app/vendor/bundle/ruby/2.6.0/gems/sqreen-1.19.1/lib/sqreen/graft/hook.rb:244:in `each'
2020-06-03T04:33:03.179578+00:00 app[web.2]: /app/vendor/bundle/ruby/2.6.0/gems/sqreen-1.19.1/lib/sqreen/graft/hook.rb:244:in `block (3 levels) in wrapper'
2020-06-03T04:33:03.179579+00:00 app[web.2]: /app/vendor/bundle/ruby/2.6.0/gems/sqreen-1.19.1/lib/sqreen/graft/call.rb:126:in `measure'
2020-06-03T04:33:03.179579+00:00 app[web.2]: /app/vendor/bundle/ruby/2.6.0/gems/sqreen-1.19.1/lib/sqreen/graft/hook.rb:243:in `block (2 levels) in wrapper'
2020-06-03T04:33:03.179579+00:00 app[web.2]: /app/vendor/bundle/ruby/2.6.0/gems/sqreen-1.19.1/lib/sqreen/graft/call.rb:126:in `measure'
2020-06-03T04:33:03.179580+00:00 app[web.2]: /app/vendor/bundle/ruby/2.6.0/gems/sqreen-1.19.1/lib/sqreen/graft/hook.rb:126:in `block in wrapper'
```

**Comment by lloeki** [comment]
Thanks for the report.

I see this is an `/api/v1/leads/1766764` path, are you using a particular framework to handle that path?

**Comment by hashwin** [comment]
It's a vanilla ActionController::API path. 

Weird thing was I didn't see anything degrade in the app, nor was Rollbar showing this error. I happened upon it while tailing logs. It seems to be related to when there is a 404 status sent from the server.

**Comment by lloeki** [comment]
To protect the user's application, we try to be as defensive as possible about exceptions that might occur within Sqreen code, and try to catch them and report them to our backend for debugging. We do show them in logs for debugging purposes too.

Thanks for the additional information. I'll attempt a reproduction.

**Comment by lloeki** [comment]
I reproduced the issue, it is indeed happening on 404s. It is now fixed and will be included in the next patch release.
